
require('settings')
require('plugins')
-- require('colors-config.kanagawa')
-- require('colors-config.nightfox')
-- require('colors-config.tokyonight')
require('colors-config.material')
require('colors-config.colorizer-conf')
-- require('colors-config.transparent')
require('tree')
require('mappings')
require('autocmds')
require('lsp-conf.lang-server')
require('lsp-conf.nvim-cmp')
require('line')
require('tree-sitter')
require('git-conf')
require('term-conf')
require('lang-conf.rust-conf')

